### ISSUE TITLE
爬下来的viewkey 都是空列表?

### ISSUE THREAD

**Issue by xwjBupt** [look1z/91spider#6]
如题,在国外的vps上跑的,然后ubuntu 18.04 anaconda3.请问是什么原因呢?

**Comment by look1z** [comment]
viewkey是因为之前91地址变了，今天更新一个新版本，更新了绕过91新版反爬加密的机制。

**Comment by zhenglin86** [comment]
爬不到video，只能爬到缩略图

**Comment by look1z** [comment]
> 爬不到video，只能爬到缩略图

因为缩略图小，所以网速慢的话会直接下下来，之前我有比较快的vps可以秒下，现在不行了，单独测试视频下载函数是可以的。
如果网速慢，你可以单独把下载视频函数拿出来试一下。

**Comment by zhenglin86** [comment]
我直接开的是国外的vps，还是下不来。

**Comment by rogerfederal** [comment]
> > 爬不到video，只能爬到缩略图
> 
> 因为缩略图小，所以网速慢的话会直接下下来，之前我有比较快的vps可以秒下，现在不行了，单独测试视频下载函数是可以的。
> 如果网速慢，你可以单独把下载视频函数拿出来试一下。

Do you want to use proxy?[y/n]y
input your proxy config ep:"127.0.0.1:8080"127.0.0.1:1080
[['0ad487e6f45f06ce19b8''8e0d1e7500a5c17e7be4', ['0ad', 0ad487e6f45f06ce19b8'487
e6f45f06ce19b8'', 8'0ad487e6f45f06ce19b8', , e0d1e7500a5c17e7be4''7be'7bedd36134
28e, a263c1f'dd3613428ea263c1f'', '7bedd3613428ea263c1f'094, '5425fa6f054af14548
e39d2147dec910ab', , 0f3''7be'5425fa6f04afdec910ab'd, '7d5d692305fb6e6ef336', '7
d5d69d2, 305fb6e6ef336'', 36'094517b15f14584ffbb023a41'1, 454'7b15f14584ffbb0342
8823a41', '73ec18e7e7f50151a7626', '73c18e7e7f50151a7626', '205a6cac8c4d42e50362
'a, e39d'2221405a6cac8c4d42e503627'6, 0f3', ''b4a9d7710d787954d23a'd, 3c1'b4a9d7
71f0d'787954d23a', '5, 'a69db3779fe9932de408', 'a69db3779fe9932de408', 'e9509906
9c65f73ae82cbe9'425, 1'fe59a5d0699069c73ae82cbe9', 'beba2b9d8eb5bc0ac9d3', 'beba
2b9d8eb5bc0a3c9d3', '16faa14125a16e72476960e850e472f'd, 4a'66fdea125a16e74766ee4
72f'1, c9'', 701db7e55479d6282c1c', '701db7e55479d6282c1c', '8757fad7fe46d809d9c
e'', 1'd65f8757fad7fe46d809d9ce', '05983f11c38ccc0fafad', '05983f11c38ccc0fafad'
, 'fce09d3f409d37e86b13', 'fce09d3f409d37e86b13', '97e5e6221879595751e0', '97e5e
6221879595751e0', '1934834ced90ef2f7db2', '1934834c1ed90ef2f7db2', '310c1babdde2
c45da658fd', '310c1babdde2c4a658fd', 'd2449eef6e92f0fb41c2', 0ab'd2449eef6e92f0f
b41c2', '100a41c6c01ab01e23a6', '1003a'41c6c01ab01e23a6', '6b311dc361cadd51d447'
, '6b311dc361cadd51d447', 'd7193a1957ba2eaa68a9', 'd7193a1957ba2eaa68a9', '394,
'9bbd01a295afbf87e5d', '3949bbd0295afbf87e5d']
1429850d61', '2bbaba3507d3cadaf0ec', '2bbaba3507d3cadaf0ec', '59c1bb3eb93b50ed0d
34', '59c1bb3eb93b50ed0d34', '0875464dca01dad86144', '0875464dca01dad86144', '10
840e8f871c14504728', '10840e8f871c14504728', '4465e7ce4a54afac6da91a', '4465e7ce
4aaf25fa6f04afacde6dc9a9101aab', ''2173, 'cf7dc75d692305fb6e6ef336', '7d5d692305
fb6e6ef336', '7b15f14584ffbb023a41', '7b15f14584ffbb023a41', '73c18e7e7f50151a76
26', '73c18e7e7f50151a7626', '205a6cac8c4d42e50362', '205a6cac8c4d42e50362', 'b4
a9d7710d787954d23a', 'b4a9d7710d787954d23a', 'a69db3779fe9932de408', 'a69db3779f
e9932de408', 'e95099069c73ae82cbe9', 'e95099069c73ae82cbe9', 'beba2b9d8eb5bc0ac9
d3', 'beba2b9d8eb5bc0ac9d3', '6a125a16e74766ee472f', '6a125a16e74766ee472f', '70
1db7e55479d6282c1c', '701db7e55479d6282c1c'0ec9e16a[, 'a87'67aab38097f027b07e',
'a767aab38097f0287577b07e', 'a6889f37f5b8fa561ee3', 'a6889f37f5b8ffa561ee3', '34
8b6ce900bb0ccc2682', '348b6ce900bb0ccc2682', '9ced2dcd803458fc3c76', '9ced2dcd80
34ad7f58fc3c76', '138b37af3c235726ca54', '13e8b37af3c235726ca54', '1a39114dba5aa
dce795b', '1a39114dba5aadce795b', 'e4e66b890cbe39d2bdf2', 'e4e66b890cbe39d2bdf2'
, 4'fd4aa9a653a47f2c5e272'6, 2d''d4aa9a653a47f2c5e272', '31a0a2d06e233d5395739',
 '31a0a206809e233dd, 53957939c'', e''7d7dfef74165729225e5', '7d7dfef74165729225e
5', '0ff74609b01cd8affd77', '0ff74609b01cd8affd77', , 2173cfc70ec9e16a8f2d''4a0a
7ac465dd19f6c79d', '4a0a7ac465dd19f6c79'd'8, , 7'6c95772ac77d78247c99cb', '6c972
ac77d78247c99cb', '84154e9f22c3e16c3bfab7', d''874a1f524e9f22c3e16c3bb7'e, aa6'f
a40b8f631cae1594a6dad2b'5, 46'dfda840861ae1594a6dad2b'7, 809'246caf0c821ac323378
3', '246caf0c821ac3233783', '80547a70c5249d53850e', '80547a70c5249d53850e', 'cb0
d3ea00f84a8a99420', 'cb0d3ea00f84a8a99420', '1ff69e73858fbc199f65', '1ff69e73858
fbc199f65', '5ce3031c1c8a74ec7c9d', '5ce3031c1c8a74ec7c9d', '81b8ac4ac6ec59a344b
3', '81b8ac4ac6ec59a344b3', '72666a94b92ce8294d31', '72666a94b92ce8294d31', 'c27
7d0092eec538d4238', 'c277d0092eec538d4238', '9360d5ae83b7d041509e'fe[, d9'f'c9e3
603abad5eae83b27ed'0411493509e''],
91c0b9860a224', 'a2aa6, '05'f3aba9391c0b9860a224'98, bf'8915f62eed1934ec3b85', '
8915f62eed1934ec3b85', 'f06223a133488e0f20c0', 'f06223a133488e0f20c0', '5ee06746
6ef5c08fe5d0', '5ee063f746116ef5c3c08c3fe5d5d8c0', '7650f98d0dd35c9ff5cc0faf4687
', '7650f98d0dd35c9ff546', '8e133eaf978c0c9b1f24', '8e133eaf978c0c9b1f24', '6334
6f935a8fadaebb02', '63346f935a8ffeadadaeb', b02'', 'e0059aee03981e214'6d3fa3, 'f
c7f0f2d', 'e09a031e6da315fc117f0f2d', '30426b6571ce2a11b2ab'34, 'c33089428c6b657
1ce2a11b2e3abcc'0b, 'ed819fcd80f6eb2568b213', 'ed819fcd86eb2568b213', '18272832f
fbeca3b435b', '18272832ffbeca3b435b', 'b340d558f56d3b25c2fc', 'b340d558f56d3b25c
2fc', '04bd316954063e636005', '04bd316954063e636005af', '1f32c0240d9f34057d83',
'1f32c024022d9f34057d83', '3a39ce6ef7755cd134fd', '3a39ce6ef7755cd134fd', '9461b
bc94621381336c7', '9461bbc94621381336c7', 'f0712b3ca20a3c1ea100', 'f0712b3ca20a3
c1ea100', '85ffcaa3222eaabc6542', '85ffcaa3222eaabc6542', '066c80a6045448d73e98'
, '066c80a6045448d73e98', 'a13e2276781a9d4de6b7', 'a13e2276781a9d4de6b7', 'fae4d
bce2aba97eb6021', 'fae4dbce2aba97eb6021', '469606005807f71035a1', '469606005807f
71035a1', 'fada0632aeb0bbb0a2b092', 'fa0632aeb0bbb0a2b092', 'bf14518088f5046d61a
4', 'bf14518088f5046d61a4']
0ec6c9bc', '153489e30b220ec6c9bc', '039f1924614ac2d251ee', '039f1924614ac2d251ee
', '4770337ec95ea346e2db', '4770337ec95ea346e2db', '89ad5dc4f81a104eb330', '89ad
5dc4f81a104eb330', '7f444c50fc91ec99ecfb', '7f444c50fc91ec99ecfb', '5f74d6b71407
33bdbbbc', '5f74d6b7140733bdbbbc', '212c2f73395fcd71ad0e', '212c2f73395fcd71ad0e
', 'cb39b9c9ff4c16095230', 'cb39b9c9ff4c16095230', '35d516923619a5be1122', '35d5
16923619a5be1122', '9606508cc743eff3a1c2', '9606508cc743eff3a1c2', '690188b905f3
5a69777b', '690188b905f35a69777b', '2ea55469ecc146f36885', '2ea55469ecc146f36885
', '831b55ece2bfa9e5b196', '831b55ece2bfa9e5b196', '298916e9e23f07c9718c'', 'fce
09d3f4, '298916e9e23f07c9718c']09d37e86b13', 'fce09d3f409d37e86b13', '97e5e62218
79595751e0'
, '97e5e6221879595751e0', '1934834ced90ef2f7db2', '1934834ced90ef2f7db2', '310c1
babdde2c4a658fd', '310c1babdde2c4a658fd', 'd2449eef6e92f0fb41c2', 'd2449eef6e92f
0fb41c2', '100a41c6c01ab01e23a6', '100a41c6c01ab01e23a6', '6b311dc361cadd51d447'
, '6b311dc361cadd51d447', 'd7193a1957ba2eaa68a9', 'd7193a1957ba2eaa68a9', '3949b
bd0295afbf87e5d', '3949bbd0295afbf87e5d']

start to download:

start to download:
start to download:

start to download:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\PY\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PY\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "L:\Video\91porn-spider-master\test.py", line 146, in spider
    download_mp4(str(video_url[0]), str(t), my_proxies=my_proxies)
  File "L:\Video\91porn-spider-master\test.py", line 54, in download_mp4
    req=requests.get(url=url, proxies=my_proxies, headers=headers)
  File "C:\PY\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\PY\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\PY\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\PY\lib\site-packages\requests\sessions.py", line 459, in prepare_requ
est
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\PY\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\PY\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'h': No schema supplied. Perhaps you meant http://h?


已存在文件夹,跳过,强制下载

已存在文件夹,跳过,强制下载

已存在文件夹,跳过,强制下载
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\PY\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PY\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "L:\Video\91porn-spider-master\test.py", line 146, in spider
    download_mp4(str(video_url[0]), str(t), my_proxies=my_proxies)
  File "L:\Video\91porn-spider-master\test.py", line 54, in download_mp4
    req=requests.get(url=url, proxies=my_proxies, headers=headers)
  File "C:\PY\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\PY\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\PY\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\PY\lib\site-packages\requests\sessions.py", line 459, in prepare_requ
est
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\PY\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\PY\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'h': No schema supplied. Perhaps you meant http://h?

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\PY\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PY\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "L:\Video\91porn-spider-master\test.py", line 146, in spider
    download_mp4(str(video_url[0]), str(t), my_proxies=my_proxies)
  File "L:\Video\91porn-spider-master\test.py", line 54, in download_mp4
    req=requests.get(url=url, proxies=my_proxies, headers=headers)
  File "C:\PY\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\PY\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\PY\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\PY\lib\site-packages\requests\sessions.py", line 459, in prepare_requ
est
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\PY\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\PY\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'h': No schema supplied. Perhaps you meant http://h?


报错了
